line-length = 120
target-version = "py39"

[lint]
select = ["E", "F", "I", "W"]

[lint.per-file-ignores]
"tests/**" = ["E501"]
"app/importing/**" = ["E501"]
"app/calculating.py" = ["E501"]
"app/reporting.py" = ["E501"]
"app/jobs.py" = ["E501"]
